name: Continuous Releases

on: [push, pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: set up node and pnpm
        run: |
          corepack enable
          pnpm i

      - name: Compile
        run: pnpm build

      - name: Release
        run: pnpm dlx pkg-pr-new publish