name: Continuous Releases

on: [push, pull_request]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6

      - uses: pnpm/action-setup@v5
        with:
          run_install: true

      - name: Compile
        run: pnpm build

      - name: Release
        run: pnpm dlx pkg-pr-new publish